### ISSUE TITLE
Warning for static port setting

### ISSUE THREAD

**Issue by joy20man** [UFGInsurance/mulint#62]
[warning]  Global acc-claim-system-api_HTTPS_Request port: expected matching /^\${.+}$/ but was "443"
[warning]  Global acc-base-proxy_HTTPS_Request port: expected matching /^\${.+}$/ but was "443"

Since this value is always going to be 443 it doesn't seem appropriate to force it to be parameter. Recommend an exception allowing default port of 443 on request configurations.

**Comment by TrueWill** [comment]
@joy20man Thanks for opening this! I'm checking with the C4E before making the change.

**Comment by UKachegere** [comment]
@joy20man @TrueWill  
It is true that the https.port variable in properties file is used by http requests within a flow to other API's. While in most instances the value is always standard https port 443, in case of UFG depending number of domain projects used,  the ports will be different for API's hosted in mulesoft.

**Comment by TrueWill** [comment]
@joy20man As @UKachegere mentioned, we're considering moving to multiple domain projects, which means that (per @aoathout ) a Mule server would be listening on different ports for each domain project. For external calls we'd reroute traffic.

This means that the port _can_ change, so please continue to use parameters. Thank you!
